name: Run Tests

env:
  DBHOST: ${{ secrets.DBHOST }}
  DBUSER: ${{ secrets.DBUSER }}
  DBPASSWORD: ${{ secrets.DBPASSWORD }}
  DBPORT: ${{ secrets.DBPORT }}
  DBNAME: ${{ secrets.DBNAME }}

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name : Install MySQL
        run: |
          sudo apt-get update
          sudo systemctl start mysql.service
          sudo mysql --user=${{ secrets.DBUSER }} --password=${{ secrets.DBPASSWORD }} -e "CREATE DATABASE IF NOT EXISTS ${DBNAME};"

      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install All Dependencies
        run: npm install
        
      - name: Creating log folder and file
        run: |
            sudo mkdir -p /var/log/webapp
            sudo touch /var/log/webapp/logger.log

      - name: Running Integration Test
        run: npm test
