name: Valid Packer CI

on:
  pull_request:
    branches:
      - main


jobs:
  validate-packer:
    name: Zip Application and Authenticate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Zip Application
        run: zip -r webapp.zip .

      - name: Authenticate with Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.AMRESH_DEVKEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Use gcloud CLI
        run: gcloud info

      - name: Install Packer
        run: packer init ./packer/packer.pkr.hcl

      - name: FMT Packer
        run: packer fmt ./packer/packer.pkr.hcl

      - name: Run Packer validate
        run: packer validate ./packer/packer.pkr.hcl